### ISSUE TITLE
Allow display by group

### ISSUE THREAD

**Issue by mkoo** [BNHM/bnhm-directory-wp#1]
Need a way to group the directory listings by Group (within a selected museum)

Perhaps add a short code option that to show a specific group too. For example on the page instead of a generic code ` [print_bnhm_directory_alphabetical]` we could have the option of `[print_bnhm_directory_groupname]`

**Comment by jdeck88** [comment]
ok, I created a shortcode called [print_bnhm_directory_groupname]... try it out for MVZ.  If you want additional features or want me to fix something, create another issue and give me a link with the MVZ [print_bnhm_directory_groupname] code active.
