### ISSUE TITLE
Allow more options on display table

### ISSUE THREAD

**Issue by mkoo** [BNHM/bnhm-directory-wp#2]
_Interest_ could be an optional field to display under _Position_ 

Basically I am trying to see if we can closely replicate the current PHP driven directory listings on the MVZ site: http://mvz.berkeley.edu/Directory.php!

Needed for MVZ website 3.0

**Comment by mkoo** [comment]
Expanding on this request as we were planning to launch the new website in late summer.
allow for the following fields to be displayed as new options (maybe a checklist of options to display?)

- Position
- Interests

**Comment by jdeck88** [comment]
Added interests to the directory listing. see for example: https://bnhm.berkeley.edu/directory/
Position is already listed in the output.
I don't think we should add a checkbox... would clutter interface.... if really need then open a new issue for it?
